# Generated by Django 6.0.1 on 2026-01-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='linkedin_link',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='preferred_language',
            new_name='preferred_lang',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expected_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
